#importar imagen base de python
FROM python:3.12-slim

#crear en el contenedor la carpeta de trabajo
WORKDIR /app

#copiar los requerimientos al contenedor
COPY requirements.txt .

#instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

#copia el codigo del servidor
COPY ./app ./app

#exponer el puerto de trabajo
EXPOSE 5000

#comando a ejecutar para levantar el servidor
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]